extensions:
  clientaddrmiddleware: {}

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
        include_metadata: true
        middlewares:
          - id: clientaddrmiddleware
      http:
        endpoint: localhost:4318
        include_metadata: true
        middlewares:
          - id: clientaddrmiddleware

processors:
  attributes/example:
    actions:
      - key: client.addr
        action: upsert
        from_context: client.address

exporters:
  debug:
    verbosity: detailed

service:
  extensions:
    - clientaddrmiddleware
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes/example]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [attributes/example]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [attributes/example]
      exporters: [debug]
  telemetry:
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: '127.0.0.1'
                port: 8889
