name: changelog-otelbench

on:
  pull_request:
    branches:
      - main
    paths:
      # any change in the go files will cause this workflow to run
      - loadgen/cmd/otelbench/**/*.go

jobs:
  changelog:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      PR_HEAD: ${{ github.event.pull_request.head.sha }}
    # dismiss PRs from dependabot and elastic-renovate-prod
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'elastic-renovate-prod[bot]'}}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # we need the commit history

      - uses: actions/setup-go@v6
        with:
          go-version-file: internal/tools/go.mod
          cache: 'false'

      - name: Cache go tools
        id: go-tools-cache
        uses: actions/cache@v5
        with:
          path: ./.tools
          key: go-tools-${{ runner.os }}-${{ hashFiles('internal/tools/go.sum') }}

      # If there is no cache with the go tools,
      # install them. We need the changelog
      # tool for this workflow to work.
      - name: Install tools
        if: steps.go-tools-cache.outputs.cache-hit != 'true'
        run: |
          make install-tools

      - name: Ensure ./loadgen/cmd/otelbench/.chloggen/.chloggen/*.yaml addition(s)
        run: |
          if [[ 1 -gt $(git diff --diff-filter=A --name-only $(git merge-base origin/main $PR_HEAD) $PR_HEAD ./loadgen/cmd/otelbench/.chloggen | grep -c \\.yaml) ]]
          then
            echo "No changelog entry was added to the ./loadgen/cmd/otelbench/.chloggen/ directory."
            echo "Please add it running `make chlog-new` from ./loadgen/cmd/otelbench directory."
            false
          else
            echo "A changelog entry was added to the ./loadgen/cmd/otelbench/.chloggen/ directory."
          fi

      - name: Ensure no changes to the ./loadgen/cmd/otelbench/CHANGELOG.md
        run: |
          if [[ $(git diff --name-only $(git merge-base origin/main $PR_HEAD) $PR_HEAD ./loadgen/cmd/otelbench/CHANGELOG.md) ]]
          then
            echo "./loadgen/cmd/otelbench/CHANGELOG.md should not be directly modified."
            echo "Please add an entry to the changelog by running `make chlog-new`."
            false
          else
            echo "./loadgen/cmd/otelbench/CHANGELOG.md was not modified."
          fi

      - name: Validate loadgen/cmd/otelbench/.chloggen/*.yaml changes
        working-directory: loadgen/cmd/otelbench
        run: |
          make chlog-validate || { echo "New ./.chloggen/*.yaml file failed validation."; exit 1; }